export const products = [
  // ===== ORIGINAL HOMEPAGE PRODUCTS (IDs 1-8) =====
  {
    id: 1,
    name: "Readable Content",
    category: "Bags",
    price: 80.0,
    oldPrice: null,
    rating: 5,
    image: "/assets/products/backpack.jpg",
    badge: "NEW",
    description:
      "Premium leather backpack with adjustable straps and multiple compartments.",
    stock: 25,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    id: 2,
    name: "Characteristic",
    category: "Shoes",
    price: 83.6,
    oldPrice: 88.0,
    rating: 4,
    image: "/assets/shoes-oxford.webp",
    badge: "SALE",
    discountPercent: 20,
    description: "Classic Oxford leather shoes, hand-stitched finish.",
    stock: 14,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    id: 3,
    name: "Believable",
    category: "Wallets",
    price: 160.0,
    oldPrice: null,
    rating: 4,
    image: "/assets/wallet.webp",
    badge: "NEW",
    description: "Genuine leather zip wallet with anchor charm.",
    stock: 30,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    id: 4,
    name: "Readable More",
    category: "Accessories",
    price: 2800.0,
    oldPrice: null,
    rating: 4,
    image: "/assets/sunglasses.webp",
    badge: "NEW",
    description: "Designer sunglasses with UV protection lenses.",
    stock: 8,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    id: 5,
    name: "Believable",
    category: "Bags",
    price: 160.0,
    oldPrice: 200.0,
    rating: 4,
    image: "/assets/tote-bag.webp",
    badge: "NEW",
    description: "Spacious leather tote bag with detachable pouch.",
    stock: 18,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    id: 6,
    name: "Scrambled",
    category: "Accessories",
    price: 56.0,
    oldPrice: null,
    rating: 4,
    image: "/assets/belt.webp",
    badge: "NEW",
    description: "Genuine leather belt with brass buckle.",
    stock: 40,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    id: 7,
    name: "Readable Content",
    category: "Bags",
    price: 80.0,
    oldPrice: null,
    rating: 5,
    image: "/assets/backpack2.webp",
    badge: "NEW",
    description: "Compact daily-use leather backpack.",
    stock: 22,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    id: 8,
    name: "Characteristic",
    category: "Shoes",
    price: 83.6,
    oldPrice: 88.0,
    rating: 4,
    image: "/assets/products/shoes-oxford.jpg",
    badge: "SALE",
    discountPercent: 20,
    description: "Formal leather dress shoes.",
    stock: 11,
    isFeatured: false,
    isNewArrival: true,
  },

  // ===== SHOP PAGE SPECIFIC PRODUCTS (IDs 9-20) =====
  {
    id: 9,
    name: "Scrambled",
    category: "Women",
    categories: ["Women", "Fashion"],
    price: 56.0,
    oldPrice: null,
    rating: 3,
    image: "/assets/shop/1.jpg",
    badge: "NEW",
    color: "Pink",
    tags: ["Fashion", "Dress"],
    description: "Elegant patterned kimono outerwear styled for daily comfort.",
    stock: 25,
    isFeatured: false,
    isNewArrival: false,
    isShopItem: true,
  },
  {
    id: 10,
    name: "Structures",
    category: "Men",
    categories: ["Men", "Fashion"],
    price: 160.0,
    oldPrice: 200.0,
    rating: 3,
    image: "/assets/shop/3.jpg",
    badge: "SALE",
    color: "Brown",
    tags: ["Fashion"],
    description: "Classic grey suede oxford shoes with durable rubber soles.",
    stock: 14,
    isFeatured: false,
    isNewArrival: false,
    isShopItem: true,
  },
  {
    id: 11,
    name: "Generate",
    category: "Men",
    categories: ["Men", "Fashion"],
    price: 56.0,
    oldPrice: null,
    rating: 4,
    image: "/assets/shop/4.webp",
    badge: "NEW",
    color: "White",
    tags: ["Fashion", "Blazer"],
    description:
      "Light brown hooded utility parka jacket for style and rain protection.",
    stock: 30,
    isFeatured: false,
    isNewArrival: false,
    isShopItem: true,
  },
  {
    id: 12,
    name: "Believable",
    category: "Men",
    categories: ["Men", "Fashion"],
    price: 320.0,
    oldPrice: null,
    rating: 5,
    image: "/assets/shop/5.jpg",
    badge: "NEW",
    color: "Grey",
    tags: ["Fashion", "Dress"],
    description:
      "Fitted off-the-shoulder evening dress with a vibrant matching handbag.",
    stock: 8,
    isFeatured: false,
    isNewArrival: false,
    isShopItem: true,
  },
  {
    id: 13,
    name: "Readable Content",
    category: "Men",
    categories: ["Men", "Fashion"],
    price: 80.0,
    oldPrice: null,
    rating: 5,
    image: "/assets/shop/6.webp",
    badge: "NEW",
    color: "White",
    tags: ["Fashion", "Laptop"],
    description:
      "Urban camo patterned high-durability daily commuter backpack.",
    stock: 18,
    isFeatured: false,
    isNewArrival: false,
    isShopItem: true,
  },
  {
    id: 14,
    name: "Characteristic",
    category: "Accessories",
    categories: ["Accessories", "Fashion"],
    price: 83.6,
    oldPrice: 88.0,
    rating: 4,
    image: "/assets/shop/7.jpg",
    badge: "SALE",
    color: "Grey",
    tags: ["Fashion", "Clothes"],
    description:
      "Minimalist cream crewneck sweatshirt crafted from organic cotton.",
    stock: 40,
    isFeatured: false,
    isNewArrival: false,
    isShopItem: true,
  },
  {
    id: 15,
    name: "Transetting",
    category: "Accessories",
    categories: ["Accessories", "Fashion"],
    price: 120.0,
    oldPrice: null,
    rating: 5,
    image: "/assets/shop/8.webp",
    badge: null,
    color: "Grey",
    tags: ["Fashion"],
    description: "Warm knitted grey wool scarf featuring elegant ribbing.",
    stock: 22,
    isFeatured: false,
    isNewArrival: false,
    isShopItem: true,
  },
  {
    id: 16,
    name: "PopularBelief",
    category: "Women",
    categories: ["Women", "Fashion"],
    price: 60.0,
    oldPrice: null,
    rating: 5,
    image: "/assets/shop/10.webp",
    badge: "NEW",
    color: "Blue",
    tags: ["Fashion", "Clothes"],
    description:
      "Standard fit cotton tee styled with daily commuter utility gear.",
    stock: 11,
    isFeatured: false,
    isNewArrival: false,
    isShopItem: true,
  },
  {
    id: 17,
    name: "Transetting",
    category: "Women",
    categories: ["Women", "Fashion"],
    price: 120.0,
    oldPrice: null,
    rating: 5,
    image: "/assets/shop/11.webp",
    badge: "NEW",
    color: "White",
    tags: ["Fashion", "Dress"],
    description:
      "Beautiful deep blue designer dress featuring modern shoulder cutouts.",
    stock: 15,
    isFeatured: false,
    isNewArrival: false,
    isShopItem: true,
  },
  {
    id: 18,
    name: "Accompanied",
    category: "Accessories",
    categories: ["Accessories", "Fashion"],
    price: 26.0,
    oldPrice: null,
    rating: 4,
    image: "/assets/shop/12.webp",
    badge: "NEW",
    color: "Green",
    tags: ["Fashion", "Handbag"],
    description:
      "Rich emerald green leather handbag fitted with a golden shoulder chain.",
    stock: 19,
    isFeatured: false,
    isNewArrival: false,
    isShopItem: true,
  },
];

export const blogPosts = [
  {
    id: 1,
    title: "When An Unknown Printer",
    date: "Mar 14, 2121",
    excerpt:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its...",
    image: "/assets/blog1.jpg",
    author: "Admin",
    content: "Full blog content goes here.",
  },
  {
    id: 2,
    title: "Answers To Your Questions About...",
    date: "Mar 14, 2121",
    excerpt:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its...",
    image: "/assets/blog2.jpg",
    author: "Admin",
    content: "Full blog content goes here.",
  },
  {
    id: 3,
    title: "What Is Bootstrap? - The History...",
    date: "Mar 14, 2121",
    excerpt:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its...",
    image: "/assets/blog3.jpg",
    author: "Admin",
    content: "Full blog content goes here.",
  },
];

// ===== CATEGORIES =====
export const categories = [
  { id: 1, name: "Bags", slug: "bags", image: "/assets/categories/bags.jpg" },
  {
    id: 2,
    name: "Shoes",
    slug: "shoes",
    image: "/assets/categories/shoes.jpg",
  },
  {
    id: 3,
    name: "Wallets",
    slug: "wallets",
    image: "/assets/categories/wallets.jpg",
  },
  {
    id: 4,
    name: "Accessories",
    slug: "accessories",
    image: "/assets/categories/accessories.jpg",
  },
];

// ===== HOME PAGE PROMO BANNERS =====
export const banners = [
  {
    id: 1,
    title: "Women's Styles",
    image: "/assets/banners/womens-styles.jpg",
    link: "/shop?category=women",
    size: "wide",
  },
  {
    id: 2,
    title: "New Shoes",
    image: "/assets/banners/new-shoes.jpg",
    link: "/shop?category=shoes",
    size: "wide",
  },
  {
    id: 3,
    title: "Men's Accessories",
    image: "/assets/banners/mens-accessories.jpg",
    link: "/shop?category=accessories",
    size: "full",
  },
];

// ===== ORDERS (for Admin panel) =====
export const orders = [
  {
    id: 1,
    customer: "Ali Raza",
    products: [1, 3],
    total: 240.0,
    status: "Pending",
    date: "2026-06-25",
  },
  {
    id: 2,
    customer: "Sara Khan",
    products: [2],
    total: 83.6,
    status: "Delivered",
    date: "2026-06-20",
  },
  {
    id: 3,
    customer: "Bilal Ahmed",
    products: [4, 5],
    total: 2960.0,
    status: "Shipped",
    date: "2026-06-28",
  },
];

// ===== CUSTOMERS (for Admin panel) =====
export const customers = [
  {
    id: 1,
    name: "Ali Raza",
    email: "ali@example.com",
    phone: "0300-1234567",
    address: "Lahore, Pakistan",
  },
  {
    id: 2,
    name: "Sara Khan",
    email: "sara@example.com",
    phone: "0301-7654321",
    address: "Karachi, Pakistan",
  },
  {
    id: 3,
    name: "Bilal Ahmed",
    email: "bilal@example.com",
    phone: "0302-9988776",
    address: "Islamabad, Pakistan",
  },
];

// ===== REVIEWS =====
export const reviews = [
  {
    id: 1,
    productId: 1,
    user: "Ahmed",
    rating: 5,
    comment: "Great quality, fast delivery.",
  },
  {
    id: 2,
    productId: 2,
    user: "Hina",
    rating: 4,
    comment: "Good but sizing runs small.",
  },
];
